# Generated by Django 5.2.7 on 2026-02-28 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text="Human-readable address (e.g., '123 Lekki Road, Lagos')", max_length=500)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate (8 decimal precision = ~1.1mm accuracy)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate (8 decimal precision = ~1.1mm accuracy)', max_digits=10)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='core_locati_latitud_367ccc_idx'), models.Index(fields=['city', 'area'], name='core_locati_city_bf472a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('rider_current', 'Rider Current Location'), ('buyer_delivery', 'Buyer Delivery Address'), ('buyer_home', 'Buyer Home Address'), ('seller_restaurant', 'Seller Restaurant Location')], db_index=True, max_length=30)),
                ('distance_from_previous', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from previous location in km', max_digits=6, null=True)),
                ('time_since_previous_minutes', models.IntegerField(blank=True, help_text='Time elapsed since previous location in minutes', null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('clean', 'Clean - No Issues'), ('suspicious', 'Suspicious - Unusual Jump'), ('blocked', 'Blocked - Possible Spoofing')], default='clean', max_length=50)),
                ('validation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='core.location')),
                ('previous_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_previous', to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_locati_user_id_4e302c_idx'), models.Index(fields=['location_type', '-created_at'], name='core_locati_locatio_e9534c_idx')],
            },
        ),
    ]
