# Generated by Django 5.2.7 on 2026-05-06 13:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_base_fee', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Flat fee charged to buyer for deliveries up to base_distance_km (₦)', max_digits=8)),
                ('buyer_per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Additional amount charged to buyer per km beyond base_distance_km (₦/km)', max_digits=8)),
                ('rider_base_pay', models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Flat pay earned by rider for deliveries up to base_distance_km (₦)', max_digits=8)),
                ('rider_per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Additional pay earned by rider per km beyond base_distance_km (₦/km)', max_digits=8)),
                ('base_distance_km', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Distance threshold (km) before per-km rates kick in', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text="Internal notes about when/why this config was created (e.g., 'Q2 2024 pricing adjustment')", null=True)),
            ],
            options={
                'verbose_name': 'Delivery Pricing Config',
                'verbose_name_plural': 'Delivery Pricing Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
