# Generated by Django 5.2.7 on 2026-05-08 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverypricingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='base_distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Distance threshold before per-km rates kick in', max_digits=6),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='buyer_base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Flat fee charged to the buyer up to the base distance', max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='buyer_per_km_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Amount charged to the buyer per km beyond the base distance', max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one config can be active at a time'),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this pricing config', null=True),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='rider_base_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Flat pay earned by the rider up to the base distance', max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliverypricingconfig',
            name='rider_per_km_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Amount earned by the rider per km beyond the base distance', max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='deliverypricingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_delivery_pricing_config'),
        ),
    ]
