# Generated by Django 5.2.7 on 2026-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assignment_status',
            field=models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned')], default='pending_assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='assignment_timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currently_assigned_rider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_assigned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='final_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
