# Generated by Django 5.2.7 on 2026-02-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_order_assigned_at_order_assignment_status_and_more'),
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='rider.riderprofile'),
        ),
    ]
