# Generated by Django 5.2.7 on 2026-02-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_order_distance_km_order_platform_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_at_pickup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('arrived_at_pickup', 'Arrived at Pickup'), ('released_by_seller', 'Released by Seller'), ('picked_up', 'Picked Up'), ('on_the_way', 'On the Way'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
