# Generated by Django 5.2.7 on 2026-02-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_order_arrived_at_pickup_order_delivery_attempted_at_and_more'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_attempted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='released_at',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text="Buyer's currently selected location for viewing restaurants", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_current_users', to='core.location'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Default address (deprecated - use current_location)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('preparing', 'Preparing'), ('available_for_pickup', 'Ready for Pickup'), ('awaiting_rider', 'Finding Rider'), ('assigned', 'Rider Assigned'), ('arrived_at_pickup', 'Rider at Restaurant'), ('picked_up', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
