# Generated by Django 5.2.7 on 2026-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_addresscache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='addresscache',
            new_name='buyer_addre_query_h_2e84ff_idx',
            old_name='buyer_addre_query_i_hash',
        ),
        migrations.RenameIndex(
            model_name='addresscache',
            new_name='buyer_addre_latitud_cea0c2_idx',
            old_name='buyer_addre_latitu_idx',
        ),
        migrations.RenameIndex(
            model_name='locationhistory',
            new_name='buyer_locat_buyer_i_413e0f_idx',
            old_name='buyer_locat_buyer_i_idx',
        ),
        migrations.RenameIndex(
            model_name='locationhistory',
            new_name='buyer_locat_order_i_ea6d31_idx',
            old_name='buyer_locat_order_i_idx',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Buyer GPS latitude for delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Buyer GPS longitude for delivery', max_digits=10, null=True),
        ),
    ]
