# Generated by Django 5.2.7 on 2026-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('preparing', 'Preparing'), ('available_for_pickup', 'Ready for Pickup'), ('awaiting_rider', 'Finding Rider'), ('assigned', 'Rider Assigned'), ('arrived_at_pickup', 'Rider at Restaurant'), ('picked_up', 'Order Picked Up'), ('on_the_way', 'On the Way'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
