# Generated by Django 5.2.7 on 2026-03-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_pin',
            new_name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_code',
        ),
    ]
