# Generated by Django 5.2.7 on 2026-03-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_rename_delivery_pin_order_confirmation_code_and_more'),
        ('seller', '0011_menuitemcategory_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='buyer_waitl_latitud_09b861_idx'), models.Index(fields=['created_at'], name='buyer_waitl_created_60e070_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position in the waitlist queue')),
                ('group_size', models.PositiveIntegerField(default=1, help_text='Number of people in the group')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('estimated_wait_time', models.PositiveIntegerField(default=15, help_text='Estimated wait time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_waitlist_entries', to='buyer.buyerprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='seller.restaurant')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='buyer_waitl_restaur_fa7cf0_idx'), models.Index(fields=['buyer', 'status'], name='buyer_waitl_buyer_i_4b5281_idx'), models.Index(fields=['created_at'], name='buyer_waitl_created_98b944_idx')],
                'unique_together': {('buyer', 'restaurant', 'status')},
            },
        ),
    ]
