# Generated by Django 5.2.7 on 2026-04-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_merge_0010_buyerprofile_fcm_token_and_more_0015_alter_cart_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscache',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Full response from Mapbox'),
        ),
        migrations.CreateModel(
            name='BuyerOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verify_phone', 'Verify Phone Number'), ('update_profile', 'Update Profile')], default='registration', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='buyer.buyerprofile')),
            ],
            options={
                'verbose_name': 'Buyer OTP',
                'verbose_name_plural': 'Buyer OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
