# Generated by Django 5.2.7 on 2026-04-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_alter_addresscache_raw_data_buyerotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_ready', 'Order Ready'), ('order_on_delivery', 'Order on Delivery'), ('order_delivered', 'Order Delivered'), ('promotion', 'Promotion'), ('payment_failed', 'Payment Failed'), ('support', 'Support Message')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Additional notification data')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buyer.buyerprofile')),
            ],
            options={
                'verbose_name': 'Buyer Notification',
                'verbose_name_plural': 'Buyer Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', 'is_read'], name='buyer_buyer_buyer_i_ef8241_idx'), models.Index(fields=['buyer', 'created_at'], name='buyer_buyer_buyer_i_4383c1_idx'), models.Index(fields=['notification_type'], name='buyer_buyer_notific_835355_idx')],
            },
        ),
    ]
