# Generated by Django 5.2.7 on 2026-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0020_order_assignment_timeout_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyernotification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_ready', 'Order Ready'), ('rider_assigned', 'Rider Assigned'), ('rider_arrived_at_restaurant', 'Rider Arrived at Restaurant'), ('order_picked_up', 'Order Picked Up'), ('order_on_the_way', 'Order On The Way'), ('delivery_attempted', 'Delivery Attempted'), ('order_delivered', 'Order Delivered'), ('promotion', 'Promotion'), ('payment_failed', 'Payment Failed'), ('support', 'Support Message')], db_index=True, max_length=50),
        ),
    ]
