# Generated by Django 5.2.7 on 2026-05-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0021_alter_buyernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text="Buyer's email address (synced with User)", max_length=254, null=True),
        ),
    ]
