# Generated by Django 5.2.7 on 2026-05-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0022_buyerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerotp',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='buyer.buyerprofile'),
        ),
    ]
