# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0023_alter_buyerotp_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerotp',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
    ]
