# Generated by Codex on 2026-05-08

from django.db import migrations, models


def move_email_otps(apps, schema_editor):
    BuyerOTP = apps.get_model('buyer', 'BuyerOTP')
    BuyerOTP.objects.filter(
        phone_number__contains='@',
        email__isnull=True,
    ).update(email=models.F('phone_number'), phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0024_alter_buyerotp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerotp',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.RunPython(move_email_otps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='buyerotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
