# Generated by Django 5.2.7 on 2025-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(blank=True, default='30-45 mins', max_length=50),
        ),
    ]
