# Generated by Django 5.2.7 on 2025-12-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_restaurant_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='seller.sellerprofile', null=True, blank=True),
        ),
    ]
