# Generated by Django 5.2.7 on 2025-12-15 11:46

from django.db import migrations

def fix_nulls(apps, schema_editor):
    Restaurant = apps.get_model('seller', 'Restaurant')
    SellerProfile = apps.get_model('seller', 'SellerProfile')
    
    # Get any seller to assign to orphaned restaurants
    seller = SellerProfile.objects.first()
    if seller:
        Restaurant.objects.filter(seller__isnull=True).update(seller=seller)
    else:
        # No sellers exist — delete orphaned restaurants
        Restaurant.objects.filter(seller__isnull=True).delete()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_restaurant_seller'),
    ]

    operations = [
        migrations.RunPython(fix_nulls, reverse),
    ]
