# Generated by Django 5.2.7 on 2025-12-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_fix_restaurant_seller_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='seller.sellerprofile'),
        ),
    ]
