# Generated by Django 5.2.7 on 2026-01-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_restaurant_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
