# Generated by Django 5.2.7 on 2026-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_payoutdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Restaurant latitude (8 decimal precision)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Restaurant longitude (8 decimal precision)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Restaurant latitude (for future use)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Restaurant longitude (for future use)', max_digits=10, null=True),
        ),
    ]
