# Generated by Django 5.2.7 on 2026-03-14 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_rename_delivery_pin_order_confirmation_code_and_more'),
        ('seller', '0009_alter_restaurant_latitude_alter_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time FCM token was updated', null=True),
        ),
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('order_ready', 'Order Ready for Pickup'), ('order_cancelled', 'Order Cancelled'), ('delivery_assigned', 'Delivery Assigned'), ('payout_approved', 'Payout Approved'), ('new_review', 'New Review Received'), ('order_update', 'Order Status Update'), ('system_alert', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_notifications', to='buyer.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seller.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller Notification',
                'verbose_name_plural': 'Seller Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'is_read'], name='seller_sell_seller__157569_idx'), models.Index(fields=['notification_type'], name='seller_sell_notific_f9ae7a_idx')],
            },
        ),
    ]
