# Generated by Django 5.2.7 on 2026-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_menuitemcategory_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for menu item image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for menu item image', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for restaurant image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for restaurant image', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for seller profile image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for seller profile image', null=True),
        ),
    ]
