# Generated by Django 5.2.7 on 2026-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_menuitem_cloudinary_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetails',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
