# Generated by Django 5.2.7 on 2026-05-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_payoutdetails_bank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cloudinary_image_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cloudinary_image_url',
        ),
        migrations.RemoveField(
            model_name='payoutdetails',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cloudinary_image_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cloudinary_image_url',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='cloudinary_image_id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='cloudinary_image_url',
        ),
        migrations.CreateModel(
            name='RestaurantCommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, help_text='Commission percentage deducted from food orders (e.g., 10 = 10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config can be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Commission Config',
                'verbose_name_plural': 'Restaurant Commission Configs',
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0)), name='commission_percent_non_negative')],
            },
        ),
    ]
