# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_remove_menuitem_cloudinary_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetails',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
