# Generated by Django 5.2.7 on 2026-05-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_sellerotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerotp',
            name='seller',
        ),
        migrations.AlterModelOptions(
            name='restaurantcommissionconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restaurant Commission Config', 'verbose_name_plural': 'Restaurant Commission Configs'},
        ),
        migrations.RemoveConstraint(
            model_name='restaurantcommissionconfig',
            name='commission_percent_non_negative',
        ),
        migrations.RemoveField(
            model_name='payoutdetails',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='restaurantcommissionconfig',
            name='commission_percent',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for menu item image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for menu item image', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for restaurant image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for restaurant image', null=True),
        ),
        migrations.AddField(
            model_name='restaurantcommissionconfig',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage deducted from order total (e.g., 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantcommissionconfig',
            name='payout_schedule',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often restaurants are paid out', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantcommissionconfig',
            name='restaurant',
            field=models.OneToOneField(blank=True, help_text='Leave blank for global default configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_config', to='seller.restaurant'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cloudinary_image_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for seller profile image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary secure URL for seller profile image', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantcommissionconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='restaurantcommissionconfig',
            index=models.Index(fields=['restaurant'], name='seller_rest_restaur_529c39_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantcommissionconfig',
            index=models.Index(fields=['is_active'], name='seller_rest_is_acti_70d732_idx'),
        ),
        migrations.DeleteModel(
            name='SellerOTP',
        ),
    ]
