# Generated by Django 5.2.7 on 2026-05-08 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_remove_sellerotp_seller_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='restaurantcommissionconfig',
                    name='commission_percentage',
                ),
                migrations.AddField(
                    model_name='restaurantcommissionconfig',
                    name='commission_percent',
                    field=models.DecimalField(db_column='commission_percentage', decimal_places=2, default=Decimal('10.00'), help_text='Commission percentage deducted from food orders (e.g., 10 = 10%)', max_digits=5),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='restaurantcommissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0)), name='restaurant_commission_percent_non_negative'),
        ),
    ]
