# Generated by Codex on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_remove_restaurantcommissionconfig_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verify_phone', 'Verify Phone Number'), ('update_profile', 'Update Profile')], default='registration', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='seller.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller OTP',
                'verbose_name_plural': 'Seller OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
