# Generated by Django 5.2.7 on 2026-02-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='account_status',
            field=models.CharField(choices=[('pending_documents', 'Pending Documents'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending_documents', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='profile_completion_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RiderBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='rider.riderprofile')),
            ],
            options={
                'verbose_name': 'Rider Bank Details',
                'verbose_name_plural': 'Rider Bank Details',
            },
        ),
        migrations.CreateModel(
            name='RiderOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='rider.riderprofile')),
            ],
            options={
                'verbose_name': 'Rider OTP',
                'verbose_name_plural': 'Rider OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
