# Generated by Django 5.2.7 on 2026-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_riderdocument_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
