# Generated by Django 5.2.7 on 2026-02-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_phase_7_realtime_location_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='riderlocation',
            new_name='rider_rider_rider_i_1c2c71_idx',
            old_name='rider_riderlo_rider_i_idx',
        ),
        migrations.RenameIndex(
            model_name='riderlocation',
            new_name='rider_rider_current_e98975_idx',
            old_name='rider_riderlo_current_idx',
        ),
        migrations.RenameIndex(
            model_name='ridernotification',
            new_name='rider_rider_rider_i_729ffc_idx',
            old_name='rider_riderno_rider_i_idx',
        ),
        migrations.RenameIndex(
            model_name='ridernotification',
            new_name='rider_rider_notific_4b6aa9_idx',
            old_name='rider_riderno_notifi_idx',
        ),
        migrations.AddField(
            model_name='riderorder',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderorder',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderorder',
            name='status',
            field=models.CharField(choices=[('assigned_pending', 'Assigned - Pending Response'), ('accepted', 'Accepted'), ('arrived_at_location', 'Arrived at Pickup'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='assigned_pending', max_length=20),
        ),
    ]
