# Generated by Django 5.2.7 on 2026-02-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('rider', '0007_update_riderorder_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_longitude',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text="Rider's real-time current location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_current_users', to='core.location'),
        ),
        migrations.DeleteModel(
            name='RiderLocation',
        ),
    ]
