# Generated by Django 5.2.7 on 2026-03-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_rename_buyer_addre_query_i_hash_buyer_addre_query_h_2e84ff_idx_and_more'),
        ('rider', '0008_remove_riderprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Current latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Current longitude', max_digits=10)),
                ('accuracy', models.FloatField(default=0, help_text='GPS accuracy in meters')),
                ('is_tracking', models.BooleanField(default=False, help_text='Whether actively tracking this rider')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last location update timestamp')),
                ('current_order', models.ForeignKey(blank=True, help_text='Order being delivered (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_location_updates', to='buyer.order')),
                ('rider', models.OneToOneField(help_text="Rider's location record", on_delete=django.db.models.deletion.CASCADE, related_name='current_location_data', to='rider.riderprofile')),
            ],
            options={
                'verbose_name': 'Rider Location',
                'verbose_name_plural': 'Rider Locations',
                'indexes': [models.Index(fields=['rider', 'updated_at'], name='rider_rider_rider_i_e01808_idx'), models.Index(fields=['is_tracking'], name='rider_rider_is_trac_b3eb99_idx')],
            },
        ),
    ]
