# Generated by Django 5.2.7 on 2026-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0010_riderprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude for distance calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude for distance calculations', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Last timestamp of location update', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='location_accuracy',
            field=models.FloatField(default=0, help_text='GPS accuracy in meters'),
        ),
    ]
