# Generated by Django 5.2.7 on 2026-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0012_riderservicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='account_status',
            field=models.CharField(choices=[('pending_documents', 'Pending Documents'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='pending_documents', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
