# Generated by Django 5.2.7 on 2026-03-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0014_align_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time FCM token was updated', null=True),
        ),
    ]
