# Generated by Django 5.2.7 on 2026-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0017_riderbankdetails_unique_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], default='registration', max_length=20),
        ),
    ]
