# Generated by Django 5.2.7 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0019_unique_pending_rider_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_base_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Flat fee charged to buyer up to base distance (in NGN)', max_digits=6)),
                ('buyer_per_km_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount charged to buyer per km beyond base distance (in NGN)', max_digits=6)),
                ('rider_base_pay', models.DecimalField(decimal_places=2, default=300.0, help_text='Flat pay earned by rider up to base distance (in NGN)', max_digits=6)),
                ('rider_per_km_rate', models.DecimalField(decimal_places=2, default=60.0, help_text='Amount earned by rider per km beyond base distance (in NGN)', max_digits=6)),
                ('base_distance_km', models.DecimalField(decimal_places=2, default=3.0, help_text='Distance threshold before per-km rates kick in (in km)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Pricing Config',
                'verbose_name_plural': 'Delivery Pricing Config',
                'constraints': [models.CheckConstraint(condition=models.Q(('buyer_base_fee__gte', 0)), name='buyer_base_fee_non_negative'), models.CheckConstraint(condition=models.Q(('buyer_per_km_rate__gte', 0)), name='buyer_per_km_rate_non_negative'), models.CheckConstraint(condition=models.Q(('rider_base_pay__gte', 0)), name='rider_base_pay_non_negative'), models.CheckConstraint(condition=models.Q(('rider_per_km_rate__gte', 0)), name='rider_per_km_rate_non_negative'), models.CheckConstraint(condition=models.Q(('base_distance_km__gte', 0)), name='base_distance_non_negative')],
            },
        ),
    ]
