# Generated by Django 5.2.7 on 2026-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0020_deliverypricingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridernotification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Order Assigned'), ('status_update', 'Order Status Update'), ('pickup', 'Order Picked Up'), ('delivery', 'Order Delivered'), ('rating', 'New Rating Received'), ('payout', 'Payout Approved'), ('dispute', 'Dispute Update'), ('suspension', 'Account Suspension'), ('warning', 'Performance Warning')], max_length=20),
        ),
    ]
