# Generated by Django 5.2.7 on 2026-05-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0021_alter_ridernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderotp',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='riderotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riderotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verify_phone', 'Verify Phone Number')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderotp',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='rider.riderprofile'),
        ),
    ]
